global:
  scrape_interval:     15s
  evaluation_interval: 15s

scrape_configs:
  - job_name: 'nodeexporter'
    scrape_interval: 5s
    static_configs:
      - targets:  NODE_EXPORTER_IPS_REPLACE_STRING

  - job_name: 'cadvisor'
    scrape_interval: 5s
    static_configs:
      - targets:  CADVISOR_IPS_REPLACE_STRING

  - job_name: 'prometheus'
    scrape_interval: 10s
    static_configs:
      - targets: ['127.0.0.1:9090']